in_distribution_datasets = [
    'MNIST', 'Fashion_MNIST', 'KMNIST', 'Letters',
    'CIFAR10', 'SVHN',
]
out_of_distribution_datasets = [
    'MNIST', 'Fashion_MNIST', 'KMNIST', 'Letters', 'noMNIST', 'omniglot', 'CIFAR10-BW',

    'Food101', 'LSUN_crop', 'LSUN_resize', 'Flowers102', 'Caltech101', 'GTSRB',
    'CIFAR10', 'CIFAR100', 'SVHN', 'TinyImagenet', 'EuroSAT', 'DTD',

]

[hyperparameters]
# In case you want to use a different batch size for a certain dataset, use the name of the dataset
# as the variable to define the batch size
batch_size = 512

[model_type]
    [model_type.Fully_connected]
        'MNIST' = [200, 10]
        'Fashion_MNIST' = [200, 10]
        'KMNIST' = [200, 10]
        'Letters' = [200, 26]

    [model_type.ConvNet]
        'MNIST' = [300, 10]
        'Fashion_MNIST' = [300, 10]
        'KMNIST' = [300, 10]
        'Letters' = [300, 26]
        'CIFAR10' = [100, 10]
        'SVHN' = [100, 10]