[MNIST]
input_size = [1, 28, 28]
classes = 10

[Fashion_MNIST]
input_size = [1, 28, 28]
classes = 10

[KMNIST]
input_size = [1, 28, 28]
classes = 10

[Letters]
input_size = [1, 28, 28]
classes = 26

[Flowers102]
input_size = [3, 400, 400]
classes = 102

[CIFAR10-BW]
input_size = [3, 32, 32]
classes = 10

[noMNIST]
input_size = [1, 28, 28]
classes = 0

[omniglot]
input_size = [1, 28, 28]
classes = 0

[CIFAR10-BW]
input_size = [1, 28, 28]
classes = 0

[MNIST-C]
input_size = [1, 28, 28]
classes = 0