# If classes are 0, means the dataset is only used as OOD
[MNIST]
input_size = [1, 28, 28]
classes = 10

[Fashion_MNIST]
input_size = [1, 28, 28]
classes = 10

[KMNIST]
input_size = [1, 28, 28]
classes = 10

[Letters]
input_size = [1, 28, 28]
classes = 26

[CIFAR10]
input_size = [3, 32, 32]
classes = 10

[CIFAR100]
input_size = [3, 32, 32]
classes = 100

[GTSRB]
input_size = [3, 32, 32]
classes = 0

[OODGenomics]
input_size = [4]
classes = 10

[SVHN]
input_size = [3, 32, 32]
classes = 10

[NMNIST]
input_size = [2, 34, 34]
classes = 10

[CIFAR10DVS]
input_size = [2, 128, 128]
classes = 10

[DVSGesture]
input_size = [2, 128, 128]
classes = 11

[POKERDVS]
input_size = [2, 35, 35]
classes = 4

[DVSLip]
input_size = [2, 128, 128]
classes = 100

[NCALTECH101]
input_size = [2, 128, 128]
classes = 100