[paths]
results = './results'  # Single quotation for literal strings
logs = './logs'
pretrained_weights = './weights/pretrained'
datasets = './datasets'
weights = './weights'
figures = './figures'
tensorboard = './logs/tensorboard-runs'