in_distribution_datasets = ['CIFAR100']
out_of_distribution_datasets = [
    'CIFAR100','Flowers102', 'FGVCAircraft', 'Caltech101', 'DTD', 'CelebA', 'FER2013', 'Country211'
]

[hyperparameters]
# In case you want to use a different batch size for a certain dataset, use the name of the dataset
# as the variable to define the batch size
batch_size = 64

[model_arch]
    [model_arch.ConvNet]
        'CIFAR10' = [128, 10]
        #'CIFAR100' = [300, 100]