in_distribution_datasets = ['CIFAR10']
out_of_distribution_datasets = [
    'TinyImagenet', 'EuroSAT',
    'CIFAR100','Flowers102',
    'DTD',
    'Caltech101',
    'GTSRB',
]

[hyperparameters]
# In case you want to use a different batch size for a certain dataset, use the name of the dataset
# as the variable to define the batch size
batch_size = 512

[model_arch]
    [model_arch.ConvNet]
        'CIFAR10' = [100, 10]
        #'CIFAR100' = [300, 100]